// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://foogqtbkxpimonkhjhul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvb2dxdGJreHBpbW9ua2hqaHVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzc1MzAsImV4cCI6MjA1NjkxMzUzMH0.md_f402SudOf7oI9f3ICOTv6nBMZd9yzKP-fmxoEMQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);